/*
 * generated by Xtext 2.15.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.PascalRuntimeModule
import org.xtext.PascalStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PascalIdeSetup extends PascalStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PascalRuntimeModule, new PascalIdeModule))
	}
	
}
