/**
 * generated by Xtext 2.15.0
 */
package org.xtext.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>repetitive statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.pascal.repetitive_statement#getRepeatStmt <em>Repeat Stmt</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.pascal.PascalPackage#getrepetitive_statement()
 * @model
 * @generated
 */
public interface repetitive_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Repeat Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Repeat Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repeat Stmt</em>' containment reference.
   * @see #setRepeatStmt(repeat_statement)
   * @see org.xtext.pascal.PascalPackage#getrepetitive_statement_RepeatStmt()
   * @model containment="true"
   * @generated
   */
  repeat_statement getRepeatStmt();

  /**
   * Sets the value of the '{@link org.xtext.pascal.repetitive_statement#getRepeatStmt <em>Repeat Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repeat Stmt</em>' containment reference.
   * @see #getRepeatStmt()
   * @generated
   */
  void setRepeatStmt(repeat_statement value);

} // repetitive_statement
